In [1]:
import pandas as pd
import numpy as np

In [2]:
custom = pd.read_csv('../data/cs_mkt_dataset/cs_data.csv')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (31,32,33,62,63,64,93,94,95,124,125,126,221,389) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
custom.iloc[:,[31,32,33,62,63,64,93,94,95,124,125,126,221,389]]

,DMST_AST1_ITM_M1,DMST_AST2_ITM_M1,DMST_AST3_ITM_M1,DMST_AST1_ITM_M2,DMST_AST2_ITM_M2,DMST_AST3_ITM_M2,DMST_AST1_ITM_M3,DMST_AST2_ITM_M3,DMST_AST3_ITM_M3,DMST_AST1_ITM_M4,DMST_AST2_ITM_M4,DMST_AST3_ITM_M4,SEL3_ITM_M1_3,SEL3_ITM_M3_3
0,218420,5935.0,NaN,218420,005935,NaN,218420,5935.0,NaN,453540,5935.0,NaN,NaN,NaN
1,114090,34220.0,35420.0,114090,034220,035420,114090,34220.0,35420.0,114090,35420.0,302440,NaN,NaN
2,255440,30530.0,126560.0,255440,058110,030530,255440,19680.0,126560.0,255440,19680.0,126560,021040,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,034020,39130.0,89590.0,034020,039130,089590,034020,39130.0,89590.0,034020,39130.0,089590,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
803303,10140.0,NaN,NaN,10140.0,NaN,NaN,10140.0,NaN,NaN,10140.0,NaN,NaN,NaN,NaN
803304,5930.0,207760.0,7660.0,5930.0,207760.0,7660.0,5930.0,207760.0,160550.0,5930.0,207760.0,160550.0,NaN,204620
803305,194480.0,258830.0,NaN,194480.0,225570.0,258830.0,225570.0,194480.0,123420.0,225570.0,23770.0,194480.0,NaN,123420
803306,15760.0,NaN,NaN,15760.0,NaN,NaN,15760.0,NaN,NaN,15760.0,NaN,NaN,NaN,NaN
803307,99430.0,115960.0,85370.0,99430.0,115960.0,85370.0,99430.0,85370.0,115960.0,99430.0,85370.0,115960.0,NaN,NaN

In [4]:
custom.loc[:200000]

,AGE_TCD,MT_EP_EXIST_YN,LST_BEST_EA,LST_BEST_YM,DMST_FST_BUY_YM,DMETF_FST_BUY_YM,OVST_FST_BUY_YM,OVETF_FST_BUY_YM,DMST_FIN_BUY_YM,DMETF_FIN_BUY_YM,...,HTS_DYS_M3_3,CONN_DYS_M4_1,MTS_DYS_M4_1,HTS_DYS_M4_1,CONN_DYS_M4_2,MTS_DYS_M4_2,HTS_DYS_M4_2,CONN_DYS_M4_3,MTS_DYS_M4_3,HTS_DYS_M4_3
0,50,Y,300000000.0,202206,202007.0,202111.0,NaN,NaN,202205.0,202208.0,...,NaN,10.0,10.0,NaN,10.0,10.0,NaN,11.0,11.0,NaN
1,60,N,220000000.0,201711,201912.0,NaN,NaN,NaN,202210.0,NaN,...,NaN,8.0,7.0,3.0,4.0,4.0,NaN,9.0,9.0,1.0
2,40,N,44000000.0,202206,202105.0,NaN,202111.0,202111.0,202211.0,NaN,...,NaN,9.0,9.0,NaN,9.0,9.0,NaN,10.0,10.0,NaN
3,40,Y,210000000.0,202201,201912.0,202003.0,202009.0,202101.0,202204.0,202008.0,...,NaN,1.0,NaN,1.0,3.0,NaN,3.0,2.0,NaN,2.0
4,50,N,51000000.0,202209,202207.0,NaN,NaN,NaN,202209.0,NaN,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199996,30,N,7900000.0,202208,202106.0,NaN,202104.0,NaN,202112.0,NaN,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199997,30,N,25000000.0,201802,202001.0,NaN,NaN,NaN,202210.0,NaN,...,NaN,4.0,4.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN
199998,30,N,7400000.0,202211,202105.0,202205.0,202103.0,NaN,202207.0,202205.0,...,NaN,1.0,1.0,NaN,2.0,2.0,NaN,1.0,1.0,NaN
199999,40,N,160000000.0,202106,202003.0,NaN,202004.0,NaN,202211.0,NaN,...,NaN,10.0,10.0,NaN,9.0,9.0,NaN,11.0,11.0,NaN
200000,50,N,130000000.0,202012,201912.0,202004.0,NaN,NaN,202211.0,202105.0,...,NaN,9.0,9.0,NaN,10.0,10.0,NaN,11.0,11.0,NaN

In [5]:
custom.loc[:200000].to_csv("custom20.csv", encoding="ansi", index=False)

KeyboardInterrupt:

In [ ]:
cols=['BUY1_ITM_M1_1', 'BUY1_ITM_M1_2', 'BUY1_ITM_M1_3', 'BUY1_ITM_M2_1',
       'BUY1_ITM_M2_2', 'BUY1_ITM_M2_3', 'BUY1_ITM_M3_1', 'BUY1_ITM_M3_2',
       'BUY1_ITM_M3_3', 'BUY1_ITM_M4_1', 'BUY1_ITM_M4_2', 'BUY1_ITM_M4_3',
       'BUY1_MKT_M1_1', 'BUY1_MKT_M1_2', 'BUY1_MKT_M1_3', 'BUY1_MKT_M2_1',
       'BUY1_MKT_M2_2', 'BUY1_MKT_M2_3', 'BUY1_MKT_M3_1', 'BUY1_MKT_M3_2',
       'BUY1_MKT_M3_3', 'BUY1_MKT_M4_1', 'BUY1_MKT_M4_2', 'BUY1_MKT_M4_3']

In [ ]:
custom.loc[:200000,cols].to_csv("custom22.csv", encoding="ansi", index=False)

In [ ]:
custom.loc[200001:400000,cols].to_csv("custom40.csv", encoding="ansi", index=False)

In [ ]:
custom.loc[400001:600000,cols].to_csv("custom60.csv", encoding="ansi", index=False)

In [ ]:
custom.loc[200001:400000,cols].to_csv("custom40.csv", encoding="ansi", index=False)

In [ ]:
custom.loc[:,['BUY1_ITM_M1_1','BUY1_MKT_M1_1']].to_csv("buy_11.csv", encoding="ansi", index=False)

In [ ]:
buy11=pd.read_csv('buy_11_us.csv', encoding='ansi')
buy11

In [ ]:
buy11us= buy11[buy11['BUY1_MKT_M1_1'].isin(['나스닥', '뉴욕'])]
buy11us

In [ ]:
buy11uniq= buy11us.iloc[:,0].unique()
buy11uniq

In [ ]:
buy12= custom.loc[:,['BUY1_ITM_M1_2','BUY1_MKT_M1_2']]

buy12ov= buy12[buy12['BUY1_MKT_M1_2'].isin(['나스닥', '뉴욕'])]

buy12uniq= buy12ov.iloc[:,0].unique()
buy12uniq

In [ ]:
buy13= custom.loc[:,['BUY1_ITM_M1_3','BUY1_MKT_M1_3']]

buy13ov= buy13[buy13['BUY1_MKT_M1_3'].isin(['나스닥', '뉴욕'])]

buy13uniq= buy13ov.iloc[:,0].unique()
buy13uniq

In [ ]:
result = np.concatenate((buy11uniq, buy12uniq, buy13uniq))
len(result)

In [ ]:
result= set(result)
result

In [ ]:
len(set(result))

In [8]:
col=[]
for i in range(1,5):
    for j in range(1,4):
        col.append([f'BUY1_ITM_M{i}_{j}',f'BUY1_MKT_M{i}_{j}'])
col

[['BUY1_ITM_M1_1', 'BUY1_MKT_M1_1'],
 ['BUY1_ITM_M1_2', 'BUY1_MKT_M1_2'],
 ['BUY1_ITM_M1_3', 'BUY1_MKT_M1_3'],
 ['BUY1_ITM_M2_1', 'BUY1_MKT_M2_1'],
 ['BUY1_ITM_M2_2', 'BUY1_MKT_M2_2'],
 ['BUY1_ITM_M2_3', 'BUY1_MKT_M2_3'],
 ['BUY1_ITM_M3_1', 'BUY1_MKT_M3_1'],
 ['BUY1_ITM_M3_2', 'BUY1_MKT_M3_2'],
 ['BUY1_ITM_M3_3', 'BUY1_MKT_M3_3'],
 ['BUY1_ITM_M4_1', 'BUY1_MKT_M4_1'],
 ['BUY1_ITM_M4_2', 'BUY1_MKT_M4_2'],
 ['BUY1_ITM_M4_3', 'BUY1_MKT_M4_3']]

In [ ]:
buy21= custom.loc[:,col[3]]

buy21ov= buy21[buy21[col[3][1]].isin(['나스닥', '뉴욕'])]

buy21uniq= buy21ov.iloc[:,0].unique()
len(buy21uniq)

In [ ]:
buy22= custom.loc[:,col[4]]

buy22ov= buy22[buy22[col[4][1]].isin(['나스닥', '뉴욕'])]

buy22uniq= buy22ov.iloc[:,0].unique()
len(buy22uniq)

In [ ]:
result= result.union(set(buy21uniq))
result

In [ ]:
len(result)

In [12]:
result=set
for i in range(12):
    buy= custom.loc[:,col[i]]
    buy_ov= buy[buy[col[i][1]].isin(['나스닥', '뉴욕'])]
    buy_uniq= buy_ov.iloc[:,0].unique()
    result= result.union(set(buy_uniq))
len(result)

833

In [13]:
# 전체 해외주식 결과 (개별, etf포함)
result

{'AA',
 'AAL',
 'AAPD',
 'AAPL',
 'AAPU',
 'ABBV',
 'ABCL',
 'ABNB',
 'ABR',
 'ABT',
 'ABVC',
 'ACHR',
 'ACN',
 'ACRE',
 'ADBE',
 'ADCT',
 'ADM',
 'ADN',
 'ADP',
 'AEMD',
 'AERC',
 'AEVA',
 'AFRM',
 'AGFY',
 'AGNC',
 'AI',
 'AIMD',
 'AKAN',
 'ALB',
 'ALK',
 'ALLR',
 'ALLY',
 'AMAM',
 'AMAT',
 'AMC',
 'AMD',
 'AMGN',
 'AMKR',
 'AMRS',
 'AMST',
 'AMT',
 'AMTD',
 'AMV',
 'AMWL',
 'AMZN',
 'APE',
 'APGN',
 'APLM',
 'APPH',
 'APPS',
 'APTO',
 'APTX',
 'APVO',
 'AR',
 'ARBE',
 'ARCC',
 'ARDS',
 'ARDX',
 'ARE',
 'AREC',
 'ARI',
 'ARQQ',
 'ARR',
 'ARVL',
 'ASAN',
 'ASML',
 'ASTR',
 'ASTS',
 'ATER',
 'ATLX',
 'ATNF',
 'ATNFW',
 'ATNX',
 'ATVI',
 'ATXG',
 'ATXI',
 'AUR',
 'AUTL',
 'AUVI',
 'AVCT',
 'AVGO',
 'AVXL',
 'AVYA',
 'AWIN',
 'AWINW',
 'AXLA',
 'AXP',
 'AZUL',
 'BA',
 'BABA',
 'BAC',
 'BAER',
 'BAM',
 'BARK',
 'BBAI',
 'BBBY',
 'BBIO',
 'BCAB',
 'BCAN',
 'BDN',
 'BDRX',
 'BE',
 'BGRY',
 'BGXX',
 'BIAF',
 'BIDU',
 'BIIB',
 'BILI',
 'BILL',
 'BIOR',
 'BIRD',
 'BKKT',
 'BLDE',
 'BLK',
 'BLNK',
 'BLPH',
 'BLUE',
 'BMEA',
 'BMRN',
 'BND',
 'BNED',
 'BNGO',
 'BNTX',
 'BOTZ',
 'BOXD',
 'BPTS',
 'BRDS',
 'BRK.B',
 'BRMK',
 'BRTX',
 'BSFC',
 'BST',
 'BSTZ',
 'BTB',
 'BTI',
 'BTU',
 'BUG',
 'BVS',
 'BWEN',
 'BWV',
 'BX',
 'BXMT',
 'BXP',
 'BXRX',
 'BYND',
 'BYSI',
 'BZFD',
 'BZFDW',
 'C',
 'CACO',
 'CAT',
 'CBIO',
 'CCI',
 'CCL',
 'CDIO',
 'CDNS',
 'CDTX',
 'CELZ',
 'CENN',
 'CF',
 'CFRX',
 'CGC',
 'CHPT',
 'CHTR',
 'CHWY',
 'CIM',
 'CING',
 'CISO',
 'CLNN',
 'CLOU',
 'CLRO',
 'CLSK',
 'CLVS',
 'CLXT',
 'CMMB',
 'CMND',
 'CNCE',
 'CNEY',
 'CNTX',
 'COIN',
 'COKE',
 'COMS',
 'CORZ',
 'COSM',
 'COST',
 'CPB',
 'CPE',
 'CPG',
 'CPNG',
 'CPTN',
 'CRDO',
 'CRK',
 'CRKN',
 'CRM',
 'CROX',
 'CRSP',
 'CRWD',
 'CS',
 'CSCO',
 'CSSEL',
 'CTIC',
 'CTMX',
 'CTRM',
 'CTVA',
 'CVAC',
 'CVE',
 'CVKD',
 'CVNA',
 'CVS',
 'CVX',
 'CXAI',
 'CYAD',
 'CYRN',
 'CYTO',
 'DADA',
 'DAL',
 'DASH',
 'DAVEW',
 'DB',
 'DCFC',
 'DDOG',
 'DE',
 'DECK',
 'DGRW',
 'DHHC',
 'DHT',
 'DIS',
 'DKNG',
 'DLR',
 'DNA',
 'DNMR',
 'DOCU',
 'DOW',
 'DOYU',
 'DPZ',
 'DQ',
 'DRIV',
 'DRMA',
 'DS',
 'DVN',
 'DWAC',
 'EA',
 'EBET',
 'EBS',
 'ECC',
 'EDBL',
 'EDU',
 'EE',
 'EFC',
 'EGLE',
 'EH',
 'EL',
 'ELYS',
 'EMB',
 'ENPH',
 'ENSC',
 'ENVX',
 'ENZ',
 'EPAM',
 'EPR',
 'EQR',
 'EQT',
 'ESPR',
 'ETAO',
 'EUDA',
 'EURN',
 'EVGO',
 'EVTL',
 'EXAS',
 'EXPR',
 'F',
 'FATE',
 'FCEL',
 'FCX',
 'FFIE',
 'FIGS',
 'FLNC',
 'FRC',
 'FREQ',
 'FREY',
 'FRGT',
 'FRO',
 'FRTX',
 'FSK',
 'FSLR',
 'FSR',
 'FTCH',
 'FTNT',
 'FUBO',
 'FUSN',
 'FUV',
 'GAIN',
 'GD',
 'GE',
 'GENE',
 'GEO',
 'GERN',
 'GETR',
 'GEVO',
 'GFAI',
 'GIII',
 'GM',
 'GMBL',
 'GME',
 'GMVD',
 'GNK',
 'GOEV',
 'GOF',
 'GOGL',
 'GOLD',
 'GOOD',
 'GOOG',
 'GOOGL',
 'GOSS',
 'GOTU',
 'GOVX',
 'GRAB',
 'GROM',
 'GRRR',
 'GRRRW',
 'GRVY',
 'GS',
 'GSBD',
 'GSUN',
 'GT',
 'GTLB',
 'HARP',
 'HBI',
 'HCA',
 'HCDI',
 'HCTI',
 'HD',
 'HDB',
 'HEXO',
 'HGEN',
 'HILS',
 'HIMS',
 'HKD',
 'HLBZ',
 'HOLO',
 'HON',
 'HOTH',
 'HPCO',
 'HRZN',
 'HSCS',
 'HSTO',
 'HSY',
 'HTGC',
 'HTGM',
 'HUBC',
 'HUDI',
 'HUYA',
 'HYDR',
 'HYLN',
 'HYMC',
 'HYT',
 'IBM',
 'ICCM',
 'ICLN',
 'ICVX',
 'IDAI',
 'IDEX',
 'IEF',
 'IGOV',
 'IIPR',
 'ILAG',
 'ILMN',
 'IMMX',
 'IMPP',
 'IMRN',
 'IMVT',
 'INBS',
 'INDP',
 'INFI',
 'INM',
 'INMD',
 'INPX',
 'INTC',
 'INVO',
 'IONQ',
 'IQV',
 'IRBT',
 'ISO',
 'ISRG',
 'JAGX',
 'JD',
 'JEPQ',
 'JKS',
 'JMIA',
 'JNCE',
 'JNJ',
 'JOBY',
 'JPM',
 'JSPR',
 'JXN',
 'JZXN',
 'KAL',
 'KALA',
 'KALWW',
 'KBWB',
 'KBWY',
 'KERN',
 'KHC',
 'KLAC',
 'KMB',
 'KO',
 'KOPN',
 'KPRX',
 'KSPN',
 'LAC',
 'LASE',
 'LAZR',
 'LBRT',
 'LCID',
 'LGHL',
 'LGHLW',
 'LGMK',
 'LHDX',
 'LI',
 'LICN',
 'LICY',
 'LII',
 'LILM',
 'LIPO',
 'LIXT',
 'LLAP',
 'LLY',
 'LMND',
 'LMT',
 'LOGI',
 'LOW',
 'LPI',
 'LPX',
 'LRCX',
 'LTC',
 'LTHM',
 'LU',
 'LUCY',
 'LULU',
 'LUMN',
 'LUNR',
 'LUNRW',
 'LUV',
 'LVS',
 'LXEH',
 'LYFT',
 'LYLT',
 'LYT',
 'M',
 'MA',
 'MAIN',
 'MANU',
 'MARA',
 'MBLY',
 'MCD',
 'MCHI',
 'MCRB',
 'MDGL',
 'MDT',
 'ME',
 'MEGL',
 'META',
 'MGAM',
 'MGOL',
 'MGTA',
 'MINM',
 'MLEC',
 'MLGO',
 'MMAT',
 'MMM',
 'MMV',
 'MO',
 'MOB',
 'MOBQ',
 'MP',
 'MPW',
 'MRIN',
 'MRK',
 'MRNA',
 'MRVL',
 'MS',
 'MSCI',
 'MSFT',
 'MSGM',
 'MSTR',
 'MTC',
 'MTCH',
 'MTEM',
 'MTTR',
 'MU',
 'MULN',
 'MVLA',
 'MXCT',
 'MYSZ',
 'NAT',
 'NCLH',
 'NCPL',
 'NDAQ',
 'NEE',
 'NEGG',
 'NEM',
 'NET',
 'NEXI',
 'NFLX',
 'NIO',
 'NIR',
 'NIU',
 'NKE',
 'NKLA',
 'NNDM',
 'NNOX',
 'NOC',
 'NOGN',
 'NOGNW',
 'NOTE',
 'NOV',
 'NOW',
 'NRBO',
 'NRG',
 'NRSN',
 'NTLA',
 'NU',
 'NUWE',
 'NVAX',
 'NVCR',
 'NVDA',
 'NVDL',
 'NVDS',
 'NVO',
 'NVOS',
 'NVTA',
 'NVVE',
 'NYCB',
 'O',
 'OBSV',
 'OCEA',
 'OCEAW',
 'OCGN',
 'OHI',
 'OKYO',
 'OLED',
 'ON',
 'ONCS',
 'ONL',
 'OP',
 'OPEN',
 'OPGN',
 'OPI',
 'ORGN',
 'ORIC',
 'ORMP',
 'OSCR',
 'OTIC',
 'OTLY',
 'OTRK',
 'OUST',
 'OVV',
 'OWLT',
 'OXY',
 'PACB',
 'PACW',
 'PALI',
 'PANW',
 'PARA',
 'PATH',
 'PBA',
 'PBLA',
 'PBR',
 'PBR.A',
 'PBTS',
 'PCAR',
 'PDBC',
 'PDD',
 'PDI',
 'PDO',
 'PEAR',
 'PEP',
 'PERI',
 'PFE',
 'PFF',
 'PG',
 'PHVS',
 'PINS',
 'PKX',
 'PLL',
 'PLRX',
 'PLTNW',
 'PLTR',
 'PLUG',
 'PM',
 'PNC',
 'PRAX',
 'PRE',
 'PRQR',
 'PRTY',
 'PRVB',
 'PSHG',
 'PSNY',
 'PTRA',
 'PTY',
 'PYPL',
 'PYXS',
 'QBTS',
 'QCOM',
 'QNCX',
 'QNRX',
 'QQQ',
 'QQQM',
 'QRTEA',
 'QS',
 'QTNT',
 'QYLD',
 'RA',
 'RBLX',
 'RCL',
 'RDHL',
 'RDW',
 'REAL',
 'RENT',
 'RETA',
 'REVB',
 'RGTI',
 'RIDE',
 'RIG',
 'RIGL',
 'RIO',
 'RIOT',
 'RITM',
 'RIVN',
 'RKLB',
 'RKLY',
 'RNAZ',
 'RNER',
 'RNG',
 'ROK',
 'ROKU',
 'RSLS',
 'RTX',
 'RUBY',
 'RUN',
 'RVNC',
 'RXDX',
 'SARK',
 'SAVA',
 'SBLK',
 'SBUX',
 'SCHW',
 'SCPS',
 'SCYX',
 'SCZ',
 'SDGR',
 'SDRL',
 'SE',
 'SECO',
 'SEDG',
 'SERA',
 'SES',
 'SEV',
 'SFT',
 'SGML',
 'SHC',
 'SHFS',
 'SHOP',
 'SHPH',
 'SHV',
 'SHY',
 'SI',
 'SIDU',
 'SILO',
 'SINT',
 'SIVB',
 'SKLZ',
 'SKYW',
 'SLDP',
 'SLG',
 'SLND',
 'SLNO',
 'SLQT',
 'SM',
 'SMCI',
 'SMH',
 'SMMT',
 'SMR',
 'SNAP',
 'SNDL',
 'SNOA',
 'SNOW',
 'SNPS',
 'SOFI',
 'SONM',
 'SONN',
 'SOUN',
 'SOXQ',
 'SOXX',
 'SPCE',
 'SPG',
 'SPGI',
 'SPPI',
 'SPRB',
 'SPRC',
 'SPRO',
 'SPWR',
 'SQ',
 'SQL',
 'SQM',
 'SQQQ',
 'SRET',
 'SRNE',
 'STAG',
 'STEM',
 'STLA',
 'STNE',
 'STNG',
 'STRY',
 'SU',
 'SWK',
 'SWVL',
 'SWVLW',
 'SYTA',
 'T',
 'TAL',
 'TBLT',
 'TCBP',
 'TCDA',
 'TCOM',
 'TDOC',
 'TDUP',
 'TENX',
 'TER',
 'TGT',
 'TGTX',
 'THMO',
 'THW',
 'TLRY',
 'TLT',
 'TMC',
 'TMDI',
 'TMDX',
 'TME',
 'TNON',
 'TNXP',
 'TOPS',
 'TORO',
 'TPVG',
 'TQQQ',
 'TRKA',
 'TROW',
 'TSLA',
 'TSLL',
 'TSLQ',
 'TSLS',
 'TSM',
 'TSN',
 'TTD',
 'TUEM',
 'TUP',
 'TWLO',
 'TXN',
 'TYDE',
 'U',
 'UAL',
 'UBER',
 'UHG',
 'UNCY',
 'UNH',
 'UNP',
 'UPST',
 'USB',
 'USOI',
 'UTRS',
 'V',
 'VALE',
 'VBLT',
 'VCLT',
 'VCNX',
 'VERA',
 'VERB',
 'VERO',
 'VET',
 'VFC',
 'VGFC',
 'VGLT',
 'VHC',
 'VICI',
 'VINO',
 'VKTX',
 'VLD',
 'VLDR',
 'VLON',
 'VORB',
 'VRAX',
 'VRM',
 'VRNA',
 'VS',
 'VTGN',
 'VTIP',
 'VTLE',
 'VTNR',
 'VTRS',
 'VUZI',
 'VVOS',
 'VYNE',
 'VYNT',
 'VZ',
 'WAL',
 'WBD',
 'WE',
 'WFC',
 'WIMI',
 'WINT',
 'WISA',
 'WISH',
 'WKHS',
 'WLDS',
 'WM',
 'WMT',
 'WNW',
 'WOLF',
 'WPC',
 'WTI',
 'XELA',
 'XMTR',
 'XOM',
 'XPEV',
 'XPON',
 'XRTX',
 'YI',
 'YSG',
 'ZIM',
 'ZM',
 'ZS',
 'ZURA',
 'ZVSA'}

In [16]:
pd.DataFrame(result).to_csv('고객해외주식.csv', index=False)

In [17]:
pd.DataFrame(result)

         0
0     MCHI
1      ARE
2    ATNFW
3     SAVA
4     ESPR
..     ...
828     ON
829   GERN
830   AEVA
831   TCDA
832   AUVI

[833 rows x 1 columns]